//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_driving
{
    using System;
    using System.Collections.Generic;
    
    public partial class questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public questions()
        {
            this.answers = new HashSet<answers>();
        }
    
        public int id_question { get; set; }
        public string question_text { get; set; }
        public Nullable<int> correct_answer { get; set; }
        public string comment { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<int> is_picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answers> answers { get; set; }
        public virtual topics topics { get; set; }
    }
}
